site_name: Khalti Payment Gateway

nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - ePayment Gateway :
      - Web Checkout: khalti-epayment.md 
      - Client Integration:
        
        - Android SDK: checkout/android.md 
        - Flutter SDK: checkout/flutter/khalti-checkout.md
        - iOS SDK: checkout/ios.md     
      - Plug and Play:
        - WooCommerce: plugins/woocommerce.md    
  - API Reference:
      - Banking: checkout/diy-banking.md
      - Refund: api/refund.md
  # - Deprecated:
  #     - Andriod: checkout/deprecated_android.md
  #     - iOS SDK: checkout/deprecated_ios.md
  #     - Flutter/Dart SDK:
  #         - khalti: checkout/flutter/khalti.md
  #         - khalti_flutter: checkout/flutter/khalti-flutter.md
  #     - Web SDK (Widget Version) : checkout/web.md
  #     - API Reference:
  #       - Wallet: checkout/diy-wallet.md
  #     - Server Integration (Deprecated):
  #       - Verification: api/verification.md
  #       - Transaction:
  #         - List: api/transaction.md
  #         - Detail: api/transaction_details.md
  #         - Status: api/transaction_status.md
  #     - Plug and Play:
  #       - Opencart: plugins/opencart.md
  #       - Magento 2: plugins/magneto.md
  #       - Prestashop: plugins/prestashop.md
  #       - WHMCS Khalti Module: plugins/whmcs.md     
  #     - Resources: resources.md   
  
  - FAQ's and Gotchas: gotchas.md
  - Contribution: contribution.md
  - Contact Us: contact-us.md
theme:
  name: material
  custom_dir: overrides
  features:
    - content.code.annotate
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

  favicon: "https://d7vw40z4bofef.cloudfront.net/static/2.59.12-web19/images/favicon.png"
  icon:
    logo: "img/khalti_logo"
extra_css:
  - style/custom.css
docs_dir: content
site_dir: docs
repo_name: "khalti/docs.khalti.com"
repo_url: "https://github.com/khalti/docs.khalti.com"
edit_uri: "edit/master/content/"
copyright: "Copyright &copy; 2024 Khalti Private Limited"
# plugins:
#   - social
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/khalti"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/KhaltiOfficial"
    - icon: "fontawesome/brands/linkedin"
      link: "https://www.linkedin.com/company/khalti-digital-wallet"
    - icon: "fontawesome/brands/facebook"
      link: "https://facebook.com/khaltiofficial"
    - icon: "fontawesome/brands/instagram"
      link: "https://www.instagram.com/khaltiofficial/"
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
